plugins {
    id 'com.android.application'
}

android {
    namespace 'org.vi_server.wgserver'
    compileSdk 32
    ndkVersion "25.2.9519653"

    defaultConfig {
        applicationId "org.vi_server.wgserver"
        minSdk 21
        targetSdk 32
        versionCode 2
        versionName "1.0.0"
    }

    splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a', 'arm64-v8a'
            universalApk true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}

apply plugin: 'org.mozilla.rust-android-gradle.rust-android'

cargo {
    module  = "../wgserv"
    libname = "wgserv"
    targets = ["arm", "arm64"]
    apiLevel = 21
    profile = "release"
}

tasks.whenTaskAdded { task ->
    if (task.name == 'preBuild') {
        task.dependsOn 'cargoBuild'
    }
}
