plugins {
    id 'com.android.application'
}

android {
    namespace 'org.vi_server.wgserver'
    compileSdk 32
    ndkVersion "25.2.9519653"

    defaultConfig {
        applicationId "org.vi_server.wgserver"
        minSdk 21
        targetSdk 32
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

}
apply plugin: 'org.mozilla.rust-android-gradle.rust-android'

cargo {
    module  = "../wgserv"
    libname = "wgserv"
    // The DCIW3930 uses a 32-bit ARM userspace (armeabi-v7a).
    targets = ["arm"]
    apiLevel = 21
    profile = "release"
}